### ISSUE TITLE
Only combat stats are loading when importing sets

### ISSUE THREAD

**Issue by smirk45** [mythridium/combat-simulator#1]
Just updated to the 2.1.1 version of the sim and the import set buttons will only import my current levels.  None of: gear/spells/prayers/potions/pets/agility/astrology/food are being imported into the sim.

Only have the base game, no ToTH installed.

Tried on both Steam and iOS versions.

**Comment by mythridium** [comment]
@smirk45 

Hey, thanks for the bug report, I've just pushed a change for 2.1.2, I think that may fix the issue, do you mind reloading to get the new version and checking if that fixed the problem?

**Comment by smirk45** [comment]
Works now on both Steam and iOS.  Thanks!

**Comment by mythridium** [comment]
So happy to hear!

Fixed in 985f2c61e1c013fbf1ff94bfb57e14401d1ee4b2
