### ISSUE TITLE
autocomplete does not work for loot dropdown menu

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [mythridium/combat-simulator#12]
**Describe the bug/feature request**
While the new  dropdown menu for drop options certainly looks a lot nicer that my browser's native `<select>` styling, one thing I'm missing is autocomplete, i.e. getting quickly to one of the options by typing one (or more) starting letters.

I'm not very familiar with Vue, but this can probably be implemented pretty easily by replacing the `div > button` elements the dropdown seems to exist of and changing it to a (styled) `<select>` or `<datalist>` element. Alternatively you could probably implement it with the existing structure by simply adding an event listener to the parent div.  

**To Reproduce**
1. Go to Combat Simulator
2. Select the *Loot Options* tab.
3. Click on the "Choose Item" dropdown menu
4. Start typing a known option to quickly jump to a section/item
5. Nothing happens.

**Expected behavior**
The expected behaviour would be that the dropdown menu would immediately select the first matching option, continuing from previous input when typing within a certain timeframe, unless no matching option can be found. 

**Device:**
Web on Firefox; first tested with Frostshield Amulet.

**Save**
[save.txt](https://github.com/mythridium/combat-simulator/files/12643856/Harley.txt)

**Mod List**
```
Creator Toolkit
SEMI Core
SEMI Drop Chances
SEMI XP Per Hour
SEMI Auto Runecrafting
SEMI Auto Run
SEMI Save on Close
SEMI Auto Open
SEMI Auto Farming
SEMI Auto Loot
SEMI Auto Master
SEMI Auto Bury
SEMI Auto Sell
Flappy Chio
QuickShards
Right Click To Sell
Space Before Brackets
Shop Item Owned Indicator
Item Dashboard (MIID) (Disabled)
Mastery Pool Can Overflow
SEMI Auto Smith Bars
SEMI Auto Eat
SEMI Auto Slayer
SEMI Auto Collect Stockpiles
SEMI Auto Mine
Potion Downgrade
ETA
Undo Sell
Item Uses
SEMI Auto Gear Swap
Do I have room?
Combat Indicators
Floating Items
Township Breakdown
Action Workflows
Show Skill Modifiers
Will I Die?
Completion Log Icons
Shining Star
Kills in Combat
Bypass Agility Costs
Combat Simulator Reloaded (Disabled)
Quick Equip Manager (Disabled)
Upgrade All Potions
Tiny Passive Icons
Better Summoning Menu
Show Slayer Task Attack Style
Semi Auto Township
Real Quick Equip (Disabled)
Better Offline Recap
Right Click Equip Menu
[Myth] Combat Simulator
```

**Aditional Context**
Thanks for picking up development on the mod

**Comment by mythridium** [comment]
Hey, thanks for the issue.

I had to replace the dropdowns with the ones provided by the game because the melvor mobile app does not support native select elements, so dropdowns just did not work at all on mobile.

I will review this and see if I can add autocomplete to the dropdown.

In the mean time I would suggest selecting 'only selected monster' to filter the list down instead of showing every single item.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/7cadad56-ebe5-40af-b7c3-7b42220134b7)

**Comment by mythridium** [comment]
Thanks for the suggestion, I've added the ability to filter items by text.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/47dc519b-2ff8-406e-a297-afb14a773abf)

Added in 655d8ce7b3c13c884f2864ef288f61d2fe0c854d

**Comment by MadeOfMagicAndWires** [comment]
Thanks a lot! 

I totally forgot about it needing to work for mobile as well, makes a lot more sense that way. The filter is probably a much better solution considering that, seeing how you can only summon the keyboard when selecting an input field.

I also didn't even know about the 'only selected monster' feature so that will help as well.

Cheers
