### ISSUE TITLE
carthulu Pet does not apply to 

### ISSUE THREAD

**Issue by BasChana** [mythridium/combat-simulator#15]
**Describe the bug**
not getting doubled modifiers from having the cartography map mastery pet

**To Reproduce**
1. have pet
2. have no doubled bonuses in carto

**Comment by mythridium** [comment]
Thanks for reporting this, I've released a fix for this.

In addition, I fixed the cartography tooltips not updating to show the doubled positive modifiers.

Fixed 71dbe43bf416be338c5a803c8eabd8657e4838e1
