### ISSUE TITLE
Issue loading mod

### ISSUE THREAD

**Issue by TigerTugger** [mythridium/combat-simulator#16]
I first get this error when loading into Melvor:
![image](https://github.com/mythridium/combat-simulator/assets/75694774/592bbb52-d1de-4e20-bde6-1a3ff4250388)

Then when I go to the sidebar and try to pull the mod up I get this message:
![image](https://github.com/mythridium/combat-simulator/assets/75694774/3b78b9b7-a3ba-4f6d-82c2-a199ce8ef9f5)

 Any ideas?

**Comment by mythridium** [comment]
Hey there, you still have the old mod loading.

Remove Combat Simulator Reloaded and make sure you subscribe to the new version [Myth] Combat Simulator

**Comment by TigerTugger** [comment]
Thanks so much Myth- I had installed the new version, but didn't realize I had to also manually remove the older version.
