### ISSUE TITLE
Unassigner is not a function

### ISSUE THREAD

**Issue by justinferrier** [mythridium/combat-simulator#2]
**Describe the bug**
When I try to simulate using the mod, it gives me an error "No valid simulator data: simulation error: unassigner is not a function." This happens regardless of simulate selected or all, and whether dungeons are toggled or not.

**To Reproduce**
1. Go to Combat Simulation tab.
2. Click on gear preset 1
3. Click Simulate All

**Expected behavior**
It should generate simulation data with no errors.

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/14363828/b59fb3b5-1af2-4f42-8e85-d804d07f6cf9)

**Device:**
Browser

**Save**
Attach your save file using one of the following:

**Mod List**
SEMI Core
SEMI Drop Chances
Will I Die?
Show Skill Modifiers
ETA
Mastery Pool Can Overflow
Bypass Agility Costs
Equipment Presets
[Myth] Combat Simulator

**Comment by mythridium** [comment]
Thank you so much for reporting this issue. I've released a fix for this issue.

Fixed in 9e77d2f37a4896e8df2d8f88594a8ea9f4cfa87e
