### ISSUE TITLE
Auto-Eat Threshhold is not floored

### ISSUE THREAD

**Issue by BasChana** [mythridium/combat-simulator#22]
**Describe the bug**
the auto eat threshold in the player stat card is different from the expected AE threshhold in game.

**To Reproduce**
2. import an equipment set with an uneven amount of auto-eat threshold, 
3. check in game expected value 
4. see combat sim incorrect value

**Expected behavior**
numbers should be floored

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/106909380/85dbb46f-9143-4d44-9989-b28621bb9513)
![image](https://github.com/mythridium/combat-simulator/assets/106909380/f745afd5-a336-45dd-a5f7-0a17720c8bbe)
![image](https://github.com/mythridium/combat-simulator/assets/106909380/a792f5a8-4bea-44d8-914b-791eb2ac0f1a)

**Device:**
browser i guess

**Additional context**
thanks myth

**Save**
1. https://melvoridle.com/save/JVK1zeum

**Comment by mythridium** [comment]
Thanks for reporting this, looks like this was just a visual issue on the stats as you stated, it wasn't being floored, the underlying calculations were all correct.

Fixed in 13da7167b8d9d69568178c8bd8d07bd35ad9a1e1
