### ISSUE TITLE
Data Export doesn't work

### ISSUE THREAD

**Issue by guptadagger** [mythridium/combat-simulator#25]
**Describe the bug**
Data Export doesn't work. 

**To Reproduce**
1. Simulate combat
2. Try to export

**Expected behavior**
Data to be exported (downloaded?). 

**Screenshots**
<img width="560" alt="image" src="https://github.com/mythridium/combat-simulator/assets/58776417/34b97c33-cca1-4659-9759-d34bb628679b">

**Device:**
Version 119.0.6045.123 (Official Build) (arm64)
M2 Pro Ventura 13.6

**Save**
https://melvoridle.com/save/ni9wL45P

**Mod List**
SEMI Core
SEMI Auto Loot
SEMI Drop Chances
SEMI Auto Slayer
SEMI Auto Sell
[Myth] Combat Simulator
Shop Item Owned Indicator
Kills in Combat
Better Offline Recap
Item Uses
Show Slayer Tier
Will I Die?
Melvor Modifiers Exposed
SEMI XP Per Hour

**Comment by mythridium** [comment]
Hi there, thanks for reporting this issue, I've been able to reproduce the issue, just curious on what you are wanting to achieve with export? It seems like this was broken from before I picked up maintenance and I'm not even sure how this was meant to function.

I'm inclined to remove this, but curious about your use case.

**Comment by guptadagger** [comment]
I was hoping to use it to analyze combat data myself, so I could view the data in ways that the graphs make it difficult to do. If its not too much work to get working I'd appreciate it otherwise not that big of a deal.

**Comment by mythridium** [comment]
Thanks for the additional feedback, I've taken a look and was able to get it sorted out for you.

Fixed in 22eab15d101ba9049d0f2ebcd79d0cd2f92c288c
