### ISSUE TITLE
Was not loaded (DataCloneError)

### ISSUE THREAD

**Issue by kodohunt** [mythridium/combat-simulator#26]
**Describe the bug**
Clicking on the Combat Simulator on the left bar encounters a pop up that states

[Myth] Combat Simulator V2.4.14 was not loaded due to the following error : DataCloneError : Function object could not be cloned.Stacktrace: intializeWorker@blob:https://melvoridle.com/f99ae175-c9bc-4725-abba-6eef07a2eabe:1:158606
createWorkers@blob:https://melvoridle.com/f99ae175-c9bc-4725abba-6eef07a2eabe:1:146058

**To Reproduce**
1. Go to 'any skill tab'
2. Click on 'Combat Simulator on the left'
3. See error

**Expected behavior**
Expected the simulator page to open up.

**Device:**
Happens on Firefox, Chrome, Android

**Additional context**
The issue seems to have occurred after servers were updated with mod profiles.

**Save**
Attach your save file using one of the following:
URL save file  https://melvoridle.com/save/WbGK92MV

Any of the three is fine.

**Mod List**
[Myth] Combat Simulator
Handy Dandy Notebook
ETA
Item Uses
Show Slayer Tier
QuickShards
Shop Item Owned Indicator
Mastery Pool Can Overflow
Township Runes

**Comment by mythridium** [comment]
This is really unfortunate timing for the new update, I've just left this morning for a week for Christmas and don't have my computer with me to fix this.

I'll fix this as soon as I'm back in a week, but can't get to it before that.

**Comment by kodohunt** [comment]
It's not a problem, enjoy your time with your family. I just wanted to get it marked as something.

**Comment by mythridium** [comment]
Thanks again for reporting this, Malcs introduced a temporary fix to get this going last week, and I've implemented a fix now which should prevent this from happening once he removes his temporary fix.

Fixed in 6cf4473
