### ISSUE TITLE
FPS drops from this mod due to alternating maxed out CPU threads.

### ISSUE THREAD

**Issue by gotex007** [mythridium/combat-simulator#28]
This mod creates FPS loss in the game when it's used. All I have to do is be in combat with something, scroll down, open up Combat Simulator, and manually select 1 piece of gear (no simming required) and a couple of my CPU threads alternate between being maxed out and there is visible FPS drop (you can clearly see the attack bars stuttering) until a reload. I've done this with Combat Simulator being the only mod installed and running so it's 100% this mod.

Steam version.

**Comment by mythridium** [comment]
@gotex007 Thank you for reporting this issue, as you can imagine this is a fairly difficult one to resolve. I have a pretty high spec system so did not notice any cpu jumps to 100%, however within dev tools I was able to notice some irregular cpu activity when opening and closing equipment popup selectors. I didn't even need to be in combat for it.

I've made some changes to the equipment popups which resolved the cpu issues in dev tools and also improved the item images loading so they get streamed it, this should hopefully improve the fps hit when opening the equipment selector.

Please let me know if this improves the performance for you.

Also note that the game on steam does slowly degrade in performance, I've noticed that leaving the game open for 5+ hours in combat would introduce performance issues across the entire interface of the game, this is unrelated to combat simulator. To rule out if this was the game or combat simulator, I'd suggest closing the game, re-open it and then check the equipment selector, however I don't believe this is your problem, but wanted to make a note of it just in case.

**Comment by gotex007** [comment]
Yeah my machine is also relatively high spec. The bug was only affecting 3 out of 28 of my threads at a time, alternating between them for maxing them like 5-10 seconds each or something. As far as I can tell it seems like you managed to resolve the issue I was having now though , which is great because I only just started using mods a few days ago after playing the game for like 4 months and this mod was my gateway into Melvor mods due to its incredible usefulness now that I'm trying to progress through the latter part of the base game's combat stuff.

**Comment by mythridium** [comment]
I'm glad to hear this has resolved your issue, if you find anymore, feel free to open further github issues.

Fixed by 71a3981b6b3d7e07c1cba860acdefce86cca292a
