### ISSUE TITLE
Hvae to toggle dungeons twice to enable them on load.

### ISSUE THREAD

**Issue by gotex007** [mythridium/combat-simulator#29]
Really a minor issue, but is there a reason why on a fresh character load dungeons are default toggled off but it takes clicking it twice to enable them?

**Comment by mythridium** [comment]
Thanks for reporting this issue, I've cleaned up the logic in this area, the toggle buttons should now function as expected and dungeons and slayer tasks start as disabled on load.

Fixed in 3bb8d5189d22a18e53b2d3172e0feda0d1b6a73e
