### ISSUE TITLE
Township season modifier not applied

### ISSUE THREAD

**Issue by TimoDeus** [mythridium/combat-simulator#3]
It seems that Township modifiers are not calculated in when simulating.
Yesterday I calculated XP/hour when it was Winter in my town. Now the season changed to Solar Eclipse, which reduces monster respawn by 1.0s. Still CS shows the same XP/hour as before. Real XP gained per hour is a lot higher.

Tested on Android Beta 1.2, CS 2.14

**Comment by mythridium** [comment]
Thanks so much for reporting this, I've added this as a toggle which also updates if you import while the season is active/inactive.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/3b92c644-cc7c-4310-8277-693d08743711)

Fixed in f8fc061

**Comment by TimoDeus** [comment]
Works perfectly, thanks for fixing and for taking over this project in general!

07.09.2023 00:23:18 mythridium ***@***.***>:
