### ISSUE TITLE
Combat Simulator Error while loading a saved equipment slot

### ISSUE THREAD

**Issue by denofa** [mythridium/combat-simulator#34]
I received a generic Combat Simulator Error while loading slot 1 of my 5 saved equipment sets in combat simulator. The attached save/config file was generated.

[CombatSimIssue.txt](https://github.com/user-attachments/files/15788731/CombatSimIssue.txt)

**Comment by mythridium** [comment]
Thanks so much for reporting this issue, I've released a code change which should fix this issue, feel free to open another issue if this persists or you run into further issues.

Fixed in v3.0.51
