### ISSUE TITLE
Simulation Error | "TypeError: Cannot read properties of undefined (reading 'has')"

### ISSUE THREAD

**Issue by Griggabyte** [mythridium/combat-simulator#37]
**Describe the bug**
My gear setup is a bit strange, I'll admit. I'm trying to determine if this is efficient summoning xp/hr.
Gear goes in fine, then I select my desired enemy (Cult Member) and run the simulation on 'Selected', error returns straight away.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'the Simulate tab'
2. Click on 'Selected'
3. Popup appears

**Expected behavior**
Before updating this morning, simulation was running fine on this exact gear setup

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/52100370/85aff61c-c57f-4d69-b60d-6393f12af740)

**Device:**
Steam

**Additional context**
As stated, only happening since recent update. I'm only reporting in case it hasn't been flagged and my setup is unique somehow.

**Save**
Attach your save file using one of the following:
[Melvor Bug Report.txt](https://github.com/user-attachments/files/15799471/Melvor.Bug.Report.txt)

Any of the three is fine.

**Mod List**
[Myth] Combat Simulator
Mastery Pool Can Overflow
Handy Dandy Notebook
Kills in Combat

**Comment by mythridium** [comment]
Thanks so much for reporting this issue, this was an error introduced from the latest hotfix to the game.

I've released a fix for this issue in v3.0.53.
