### ISSUE TITLE
Conflict with out of date 'Will I Die' mod

### ISSUE THREAD

**Issue by Rick-2CA** [mythridium/combat-simulator#41]
**Describe the bug**

**To Reproduce**
1. Load the `Will I Die` mod v4.3.0 (for Melvor v1.2)
2. Open game

**Expected behavior**
No errors

**Screenshots**
N/A

**Device:**
Steam and Firefox 126.0.1 (64-bit)

**Additional context**
I should disable risky mods - but sharing in case it leads to something helpful.  Thanks for the mod!

I've also tested enabling every mod on my list except Will I Die and there are no errors in that scenario.

**Save**
```
game.combatAreaDisplayOrder is undefined

recalculateSurvivability@blob:https://www.melvoridle.com/40c6a27b-5d9d-491c-8cae-0b2f14ae226f:2461:24
setup/<@blob:https://www.melvoridle.com/40c6a27b-5d9d-491c-8cae-0b2f14ae226f:3240:24
createMethodPatcher/typeName.prototype[methodName]@https://www.melvoridle.com/assets/js/built/mod.js?11320:599:52
setPotion@blob:https://www.melvoridle.com/2edd904b-2097-4df2-a03a-717ff346c122:1:136318
resetToBlankState@blob:https://www.melvoridle.com/2edd904b-2097-4df2-a03a-717ff346c122:1:106348
load/duration<@blob:https://www.melvoridle.com/2edd904b-2097-4df2-a03a-717ff346c122:1:672855
```

Melvor Version: v1.3
Sim Version: 3.0.62

Continued in:  [dump.txt](https://github.com/user-attachments/files/15820893/dump.txt)

**Mod List**
[Myth] Combat Simulator
SEMI Core (Disabled)
Rag Core Library (Disabled)
Rag Queue Module (Disabled)
Action Workflows (Disabled)
Forgot My Hat (Disabled)
Mastery Pool Can Overflow (Disabled)
SEMI Auto Run (Disabled)
SEMI Auto Eat (Disabled)
Show Skill Modifiers (Disabled)
ETA (Disabled)
QuickShards (Disabled)
Equipment Presets (Disabled)
Show Item Sources And Uses (Disabled)
Priority Miner (Disabled)
Will I Die?
SEMI Auto Slayer (Disabled)

**Comment by mythridium** [comment]
Thanks for reporting this issue. As you've noted this is an issue with will i die which is breaking combat sim.

I've reached out to the author who has now made will i die private until they can update the mod to v1.3

If you are still subscribed to will i die, I would recommend unsubscribing as it doesn't work with the game anymore without an update.
