### ISSUE TITLE
Simulation Error

### ISSUE THREAD

**Issue by Dasboyo** [mythridium/combat-simulator#5]
This error has persisted for months now, on the old version of combat sim too. it always says the same thing "No valid simulation data: simulation error: DummySummoningRecipe is not defined."
There is no interaction issue with other mods. I've tried disabling all mods so that combat sim is the only one and it still happens. Tried uninstalling and reinstalling the game, with restarting and emptying the recycle bin inbetween.
[combat sim settings.txt](https://github.com/mythridium/combat-simulator/files/12551588/combat.sim.settings.txt)
[game save file.txt](https://github.com/mythridium/combat-simulator/files/12551589/game.save.file.txt)

**Comment by mythridium** [comment]
User advised on discord this is now working.

Fixed in bede1828010fe7b135e347b9a370e4b0993e71c7
