### ISSUE TITLE
Message: Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by sergh1o** [mythridium/combat-simulator#50]
Message: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=Intl.ListFormat,Intl.ListFormat.~locale.en,Intl.ListFormat.~locale.zh,Intl.ListFormat.~locale.fr,Intl.ListFormat.~locale.de,Intl.ListFormat.~locale.it,Intl.ListFormat.~locale.ko,Intl.ListFormat.~locale.ja,Intl.ListFormat.~locale.pt,Intl.ListFormat.~locale.es,Intl.ListFormat.~locale.ru,Intl.ListFormat.~locale.tr' failed to load.

---

Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=Intl.ListFormat,Intl.ListFormat.~locale.en,Intl.ListFormat.~locale.zh,Intl.ListFormat.~locale.fr,Intl.ListFormat.~locale.de,Intl.ListFormat.~locale.it,Intl.ListFormat.~locale.ko,Intl.ListFormat.~locale.ja,Intl.ListFormat.~locale.pt,Intl.ListFormat.~locale.es,Intl.ListFormat.~locale.ru,Intl.ListFormat.~locale.tr' failed to load.
    at Environment.init (blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:109299)
    at blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:112746
    at Global.time (blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:2691)
    at blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:112694
    at Transport.onMessage (blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:94492)
    at self.onmessage (blob:https://melvoridle.com/d6b4d317-e976-42d8-8b42-581f6db483cb:1:93880)

Melvor Version: v1.3?11526
Sim Version: 3.0.89

Expansions Enabled: TotH, AoD, ItA

Mod List:
 - [Myth] Combat Simulator

Save Game String and Sim string at PasteBin due body is too long (maximum is 65536 characters)

[Full error message](https://pastebin.com/2vZBVVef)

**Comment by mythridium** [comment]
Thanks for reporting this issue, looks like the script the game uses has changed. I've release v3.0.90 which fixes this issue.

Feel free to respond if the issue persists and I'll take another look.

Fixed in 0d9b526

**Comment by sergh1o** [comment]
Thanks, it works well now.
