### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BreadedSandwich** [mythridium/combat-simulator#53]
On launch I get this error:
Message: Error registering soft data dependency in CombatEffect with id "tes:ShadowBlast0": DataConstructionError: Could not construct CombatEffectStatGroup: Error constructing CombatEffectApplicator. CombatEffect with id: melvorAoD:Blind is not registered.

---

registerGameData@https://ios.melvoridle.com/assets/js/built/game.js:99:47
registerDataPackage@https://ios.melvoridle.com/assets/js/built/game.js:33:22
@https://ios.melvoridle.com/assets/js/built/mod.js:597:33
setup@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:199686
setup@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:696985
@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:692244

Melvor Version: v1.3?11585
Sim Version: 3.0.95

Expansions Enabled: None

Mod List:
 - SEMI Core
 - [Myth] Combat Simulator
 - SEMI Auto Farming
 - SEMI Drop Chances
 - Unlimited Offline
 - ETA
 - SEMI Auto Master
 - SEMI Auto Loot
 - Mastery Pool Can Overflow
 - Show Item Sources And Uses
 - Show Skill Modifiers
 - SEMI Auto Slayer
 - Shop Item Owned Indicator
 - SEMI Auto Sell
 - Item Uses
 - SEMI Auto Runecrafting
 - SEMI Auto Bury
 - SEMI Auto Smith Bars
 - Semi Auto Township
 - Better Offline Recap
 - SEMI XP Per Hour
 - SEMI Auto Open
 - Kills in Combat
 - Priority Miner
 - Upgrade All Potions
 - Skill Boosts
 - SEMI Auto Collect Stockpiles
 - Add Items
 - AutoSort
 - Combat Indicators
 - [Myth] Music
 - Sidebar Progress Bars
 - The Elder Scrolls
 - Adventuring
 - Enchanting

Save Game String:
        eJztW2mAHMdVfqPLshQnsZ2EQIAsI8kQsuPsrg7bAsdaSauVbK12rd1YNsIMPdO9M+3t6R5392i1cmxuSLgChhx2Lic2V8IRSMIRCBBMSLgTgmNuwhECMSaEEI4YCN/3qrunu2d2ZQmvf1G2Zqte3a9evXr1veqO450JQpHLp0RkM/5dYiiHEf16/Ns6H1u+bYU24iJbTgRhx/Kkgvgm5DRkA8tMNpu90Iod2chGZqyW25RNLH7U8TpOrO0+a6rTjVfqU3f23G7H8WPZAuKlcx6qNQJ7RS7Jkp7TimQrWzoYBHEkl7KlU47VDXzZxvh823U8W7YzPtnpeejhGRzQSddvyWWkTnvBGSeSZzJ+c88944TyLJY4ZHUdeTZnOWdFEehyORPzvU4n8Mflin5iQq5EYtuhwI96HavhOfIcpDdOOx15LiLPmPLblt90OJNxeV6JMiFfUKLsluezuVOub8/HobvkyBcybXhyJAhs+SKOdcasxgjilTH5MvzZPtmMMc75JdfzpKozjmOruSQ7zOKEjt+K27KTIz/sLDroT3aRlUfduBu4Pvh3FWudtPyWY8uXMz4XWivgyFcoLz2Nv4hdncI4mr04Jhu/kg0ecaM2Ey/mWI+4odOxlpgeZeahINBETQfu+oxfzWmf7PlOfSqKdCwvMVzsdp2wPhs6MsaqC66viXHO4VgYmNQEU4cCy9PUblacdz2snab3MHc68GxN7eV4Z9y4Hbqm+D4QnjlpWx3Lj93YUdo1bAKjSdPXIn3Z4dBqBRnpOuViBw1x+PuZWoB0nWHqq5QFVthh4qu1fc8LYi7nHP6Oy/UsPhfEVhxA2F46UGJCbhig7ZYDA7Q9MjlA2ysHB2j75NAA7RrhTi3SrhVu5iLtOjnCTVicwZhMDxLH5eggcUKOqVA5YcPM/UbydtoKe506iXJTPntCjueTu2Umn9wjJ/LJvTKbT+6TuXzyGrk5n7xWTuaT18k8kwuh45hhLXBJZq2l+vEASuRl+cwJuSWf3C2n8sk9ciuTR6BMmioLt6k0htaiboevSQW7mVJOM5/j8ALI0ddSViZbrufGK3I7WzJqhCW/jsnJKA4DL2itSF2FLFj2sbe6skS1dCLwHfEQ2zA9J5+jaJtteQgbOJInWP+k5dom+V99Jc0l5R7aNGVFK/KCnIL+YlKPUm1/CRXpFMblyJfqTrWiGBv+hUZhODbmr4p+y7HQtS1fLKNVndC1pMG6C04YWtJkg7dY0IM8CbbMr3geCjhaOLTAMlnk+G8KpEXaguN5vUjabODoiu344rLDm92O20Qnd2gb3ZDs6ah6h6bCqPyEBwF7U7XYZYyKSe5kW/MxWYXzSjZy+0aq1KEyJCbpoBVKT7vEukRyZkAbLXMQxx0rbqOzs3oOBLELHS8rqhg9y1+K5JwuPYRCBeEulfQQ5wVy7UheTi1y0IrcZn2+7Xgc9t2sQE3BEnIPmzoCqYhi+QbEn53qVSeM6oesTle+kSs6E/T82OKKfhN7gAZl/pwbyzdzCqdwEobyLTrpZVb6VjaLFfCcFfk2PRmwYHUMmU18OzNv7PktLNB3MH7YiZwwlleoKPrBshn7K5F8Lg6NwG+1oUpnFxfazst827Fs+W9kXZ7PMsf4/4B8ZZ5s9Gckny9noKnpwI5oGsilnZW4PdMDjzhQzsEkvpNDm+65MRbqu7h2h6FA5Lv1rLf8OwL5Ht0rzWYQ2lgW+V4y9mDQOxf0llx5lZFfiJsl38eCt654QbdNifh+nad1Nkneq7xyA8/15QeMJeG3AvlBjsayz0Cr9VT2ROV6+2SO9GoOy2cjr2Ejy8bueC1lJVhcxIFuy+tYpE2m3ceYmi/3M6aWy+vZH8tF8gYSFx3YJ29kW5axVd5EapOWyJtZlL2OywNpdELewkWKzMkXB13rXB1qZ8mzIL9vRdYVppl6sFiHTjHH/4MUsz49NIf9Q9TjfWpHF/SHikW7xhb4Ya5+n4qSqsl+pEi2EwPjR0ledFttiGi9m5lwP0Zeat9hHeZXLG/jBlx2z0EP1cOggUPy7azZtTzLhgnQr/nj3AHYbs6iqfgTrNj0oISaScWfZImG7jpl3U9xGowV+PAOnnspNeHCT3O/pjTDg5/JF0s48E4yK6Wl839XnpjO/t3sOp19ZDVw/GM//CyHnEy+oXbrz7FyMvvIc2kCRfLzrJwyIKv8C+Scmb+p+x7t2DAgq/uLeba3LKgPrEskv8QmU7ZbnQb2Bxj23hzvYd+g3C/ned+v/ivsKuF9VvtXcwtgar+PlLRz6L2O/FpuuZvQMPIw1yjpsm3F8uusknaoVd7fX2et8RtMJ92wxgcGBEu31AdzvG22rW4kv8kVTLpqBHEcdCL5rQHZ0sq/3eetqfs7uvqm07Tu77IHI164oPC+8Htki6FEXZxmWJcl+X3KkiE2etiTKPchJUENnnPqONF5MfkwB1LYwKpZ/kDXCbGCyH6Eo0mpicj+IdtMaUZkH8kXS0T2oxxiSktF9tE8MRXZP8oN0rZa4KP8MRtMx70MfTvelj8p0yba8qe68QzNOuvInylfkjJNnOfU5X+ea3/JB/8i+YtcW3dYZxyq4r/M1W2GQRQ1gmX5GIm+mi1gYBDGJP4VaydED7qbtL/uq4BlquG/4cImKxRbi4vytxwF9DK6aiWkj/MAweUUzG6uyN9RyXatEOL8CR4YDbdVN8m/5/r3/CWclH59Edce+Yc8ZZkGyCfZX0qh0fdYntAAG/6Rmn0ZR7Q8zp4wBBzB/0Sicxbn+qfMaRFF8s/Mdnj5k09zIBgdrQEsy7+wTBxaXfkMh76YGAnyr3qUcGCf5VGyaMyLf0N8I4fy7+QNWsG5o9YpzCi9X/Yp/8ETLEnLfyJBu2bzwZDHGOQyufXvz677vFGacHDlsvc+eP3HzN9p3k317v5MUwWWkDNtdWgJbjOUhbDHVA5IyJmrVyS13DBu29bKxNgEL3rPMdRJWIQezD4vAn0PLYmt53resVtvm+Dt40rcb62eF490AnukGwaLLowdwUW42tguVXujVO/oStV7rVSjR6R6/81SfdtOqb59QnacfoXs+KQvO7e9T3be+1H8exT/HpOd794qO9//uOyE4Oz83Adk1+UfkV3PPyC73vFx2fXh+2TXYwty1V1PyOi7HpLRT7hSu6IitUdCeclLH5bx+3sy/p6OTBydkYlXXSUTH9omexZhG47dOIRfJmTcZiBi8X8NNllU4X+fTwKpPEw+qGZYGioV2VCRjRUFZRISGarADECbLfofEZgsQfwlSxCByRKEYLIEbbssoVNKE8RhsgSBmCxBJCZLEIzJEgRjsgTBmCxBMCZLEInJEkRjsgSBmCxBDCZLEH5JExUFX/qBqNVGBWAk/5vnaZ9pRXYPltEiaHFoTils1jub6G1N9KYmekkTvZ7lmsgJ0ZAwXAx4aP6/GFyAGBgurrL0T/HyF9blKQ838Hzpd0UccZ17LAV2tpH6762P8q77pKogZBFG09+UUgiiWKgW38DeKpUN+J8ltfN8U2Y8hoAz9Mz41TxxGF6gIKputSwMrNmInoTnLUTM9byFiMS+8MC9OdU/pBAh2vO2xB1MRHTNQvmsLJuo73mbJxx83kKEiInDalD+PtkxKKBMePXCh58EItDELi+sgVxL+UaJYBPLvejRiALfvJ5dcBPbFSFXDbxFwfEkSlgviRIXT6IquSaqq2+iuggmShg8iRL9TqIEvpMoAe8kakJiLRD61o4ucAJcRaLcF70QDADXK7xXPKlGBGr7eqOKCbmboEPIE4iyFwiE2AsE4usFAsH1AoGma4FAWL1AoEVbIKhM5gnE0gsEWrIFApF0EAigm0DsvEAgel4gED8vEIigFwjE0AsEougFAnH0AoFIeoFALB0EgugmED8vEIigFwjE0AuENBBNV9nMwpPfYsTeL0Y0idBfTD1i+RdTj7A/gbgL3QoJpVKQcTXJNqt/MCVR5osU3vGKFHXAFig8KYoUdUhwv1+svoMHo6JW1YXX366+Bo6y/0fU51Cm0fdQphGsLdN4nyrTeC0s0+ieKNN4Ty7T6LIo0+i7KNPowijTGODQqRDt7YchzIGv52hFOhUBjMFAs/Qy9Xokc+oeeJDQPaN3HnhnGg0PPJxG6flIonR9JFE6P5IonR9JlF6PJEqfRxLN5MFWh0cSJSqQ8ZVhmzo8NqiPo6K+DcqhSRtfh61ejop6NYxeZsxWt0ZFnRmGypitHg0T6NAwge4ME+jHMIFeDBPMlBnovhga+sbt5nvG8O+Gwk3IhD6FXggi6Rcsv3pv2mY8F9olPRcmRseFidFnYWL0V5gYvRUmRkeFidFHYWL0UJgYHRQmxgBXxEaChk/yWNTRmWV7jTovGC6dX4Zzu0FfkCFuhy+Dsdfp7336e7/+vl5/36C/b9TfN+nvm/X3Af19S9p0uZ+t0w5wKAKn69rN5gVAm+5T2gevnptiQHj4ewmQN/rhuMx3BA3bAfbmcattgXMvCLllDlN0oObhXIErBX4T+EjgD4HvA94OuDfgyoD3Au4KeCjgjoD3Ad4GOBfgSoDjAF4CuAXgBIDZBYwfJiPQe0D1wOaBwwN1B8wOXB1IOsBzoOUAyIGJ4yoPwBv4NrBsoNcAq4FOA4sG9gysGSICEBmYMTBiQMIAgAH3At4FmgvwFnYV0FmgsQBfAbUCWAWOCugUmBfBUQ1bYgC0oTIATk5Ayzplz4EDmzECmQAekasIqih4KoqZiuKkotioKCAqioKmYSt8N7FrKecYtinsGwYWvGNoz4bH0gn8gl2uC/s4YNNPASb9NADRzwD8/CygTmKchZCDTfuhLyvnpwzao0Pu65vsAM9tTEg0/Tav18GWWkmfRWUZm/BWhIdPjrQZUG2rSCMUW7CZk6N/2O7eoIZAjkGAbvGHsecp8CnyotOnq/NTM8dGDmEHVkeRsp1Gr1XDa4MWkN/q6KLlRc7tCOra7PEhEdBSmKIoetiN4CpZGYlXuqauZzUcr2aHAZwMsVOL4hUPGax1+yhaLtGrZ6vFhgG/yuYH0c60g31kedpm5HTcmtWLg1pHXx/UHJ9PqqqjMaBiNmvStThYcvyoTwaSXmv04hq8sQNlwdYmhtF1fLh7MEnNvp0F5pxwRN9LjSyAA56DBjkGUmoGZ7ZrBPSTp079lotFCLavmZ0+h1qtRNM8kFotG6KyRm6UvElaLZ8OLb5SWnV45t3SqtnpO5dVB5+8c1ktP8y9hVmtDB5Z6OuY1fITl9WqLEhf0KxaP31TM1AArw86fHBQ09/hwmEewqxASCB0BVFRMeyvkylnhHO44KxVYUCM1i48KFRrlR8QsbUKlwVurbKD4pcvvVgqPSiMa06yLJprNT1EUNcqPiiSa5UeLsRr1RgU6bVKDwj4WoWHiPuabQ8Kf1K8L/zF5S9shZzKhrcMANaqKtvDg4Siwi7Uhp9NKi9ftbYKUg3O0ajcBgaM91oj6eNLU09Lp2Jjp081WT+3xwuFsIbnKWFlr0LXKtXCI6a18pmAd3KtIsblv2aJ2MHhukYBF87xtfKN8zxXIr8W9G9K5cXg46Gg0w2iWHnaNHEcpDlR6UUOlEdSKE9cdlwyA4veza/UJNZyBO/QuiPZA25t3Kwx6DUnpddsJ2qGbpfv6vqGg5ZJnczmMXdqmJRz+Yx7tTzzsHu1XD7vXjUve8k9zCCiKxj4XkmMXb8Jj23k2MlZMQfXNPqojl43NqYdtIPlGp7mNJUdg+sB37Jc8spSo8fm6+MTR+uHjs8euik32Pmjs6fqt87VT04uTPWXRKmThxaOzZ6oLxybKeccn7pl6nj9xNStC0MzZo4dn5pfmD0xvNrC5MnpqVxFng94b8EH54G/4HbAqIm9Os8k56RDkenFjskcHzNcmD4+e3Aybc60jYmq2BSzJg/eNj8/uUrmzOT8wtTJ24Znzs3Ommqal4lR/iwGZ4eNYHjXw/tcs7PkLfzT0VHfBljvvpI3/Ovfkfk+YP37KZwm69pT+pnA0yAQfRNo3eUhM4bWu6f8W/r17y19p7/+PSXfADwNkt43F9d9Tn1Tc931BB87rlM3uYOZLwXlAR7GsdMZmV32HdvYnzzQYSh2asADHdyyQ8t2YGplpzQIfoQng7RzTBGWzhskfSprJ4WbYN3Y1RNmrtrnEQBX5T752A+0IdYJHqfBW1EyJNqujQ8ranyYWnObRXuKbTbbeDZuvgErZ3mAtDDKISXy3fI9HDDKUrcBIJfasrvkplNPTTydg4sJFAh39tT2BgPGM5plw5LFwZ03EFvdmtUhmgdOpekhxQw+CdsVXz0kJRPSQOnCVPCsTyoPla8p5AV47kZNmJUhhSDjkwKVtQDoU3KN6nOIZhRqjsBejkaAQ404+ABmRKGHtNnUeKZV3W1RinKw1sDpW87on2LlnORztCEZg/fkQaVezikq4XJuX2mWczIlNzDwwTtsdl4mXzwN5iR7fsB85jNMAKCncxQ8yoSzu7SK5l6JtUsbxsYAMoiXxJk8ZKua3GibS8Pkne88Re4pNY83qUGI2RI/GQJdDs0GkMNbaa7j4cUibD48Ii/uvsqrk4sVPwnCtQXv4aujd2XT3K9FR3HH9pxmTEK12Yvwih1oLG4rXgeEjLX6Fxlp99X9d5Uz9/dXovBtJGrl5GSQWPzYMpeR+ywzR00/3cyR0m89c6T+B585YvqFaHFE2VddhRbTD01zxORr0+rtKelYPLl/srESRVjh/acL5CnsdN+Q7x6tYigRb7H799yNheETYHgjeb1Wfo/Mhjgc0hMYt/MkUR0fnRjdPbpndC+xcSoLR+8oBlxU4dSn33npgEi0gx70muU1e/h0Qe/OqYhBxXSsOIXcc/uEJ9jUWVR2yYfaGcvr5STzOIGbEs3cgqH6S/QpH4gNtBm+O3T9cuYM9CO+gLB8J+hF5cx03in99NhoMn+OkU+m8daktKVOOhEmi+9MwCwiC1ga9oJLZq8zMgO0n8claaHTtdywhiEt6weCQ7QEH2TjVdsAAAUYmPcofHDdP8Dz9fiI23AQKJQ9chS3LjhQEswEQ+irfd5zdTTxcurASKmG3MY3lOUMzcGBHg5kjBmhmAlsd9HVvY8O8aQ9TVXhbdMn+EXPCh+cizxRnic+PgbTMzQCX+3ONkDE5y35Q1/BwvlM2aRrhzM0tg72XHy+l1TK1aGgnnTsgyq3OmQ8uNc1qOp6wTkD9Xo26bwJAzE0Zas7xsb2XjO2DwV37Nu31xkbY2xvE1PnttyxZ/cee2+DsbGxfY3GtZgnmzNnSrIESsInDg4SA4c5390nbi+MUbEw1dNBCzUigmM1486qjhV5qA/0ZYQQfwL1o6xdp1NrqAFU/qQh87IbXx6/1C0GfqpbDPxad1jYpB9cin5fadx5Q17o/i/aOtbo

Sim String:

equipment@https://ios.melvoridle.com/assets/js/built/player.js:20:69
export@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:276780
exportAsString@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:276373
report@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:267526
@blob:https://ios.melvoridle.com/d0c5d8b8-3958-42f4-b914-c9f06633cf88:1:693365

**Comment by BreadedSandwich** [comment]
The game launches, should I worry about it? I’m not much of a modder idk what to do!

**Comment by BreadedSandwich** [comment]
Ok after some quick testing, there is a conflict with the elder scrolls mod. I hope that helps… are you willing to resolve the conflict?

**Comment by mythridium** [comment]
Hi @BreadedSandwich 

As you've discovered, this is an issue with the elder scrolls mod not combat sim. Please report this issue to the author of the elder scrolls mod, they are using an AoD only effect, but you don't own AoD so that effect doesn't exist in your game. They need to either:

- restrict the mod to require AoD, in which case you wouldn't be able to use it
- replace the effect with one that doesn't require AoD
- only use that effect if the user owns AoD

Thanks for taking the time to report this issue.
