### ISSUE TITLE
Combat simulations do not produce results

### ISSUE THREAD

**Issue by marron674** [mythridium/combat-simulator#55]
**Describe the bug**
When I try to run a combat simulation, it quickly goes through the simulation, but only gives an error.

**To Reproduce**
1. Open the game.
2. Go to combat simulator mod.
3. Simulate any target.
4. All simulations seem to return a similar error: "No valid simulation data: Cannot read properties of undefined (reading 'simulateMonster')
5. All the simulation output (e.g., XP/h) says N/A or 0.

**Expected behavior**
It should successfully simulate a dungeon.

**Screenshots**
![image](https://github.com/user-attachments/assets/c2cf85c8-49b0-44f9-8121-05efa51f26ef)

**Device:**
Desktop

**Additional context**

**Save**
[bug report.txt](https://github.com/user-attachments/files/16620790/bug.report.txt)

**Mod List**
[Myth] Combat Simulator
Show Item Sources And Uses
ETA

**Comment by mythridium** [comment]
Thanks for reporting this, the new melvor update made some changes which cause combat sim to throw an error.

Fixed in 09d666a
