### ISSUE TITLE
[Feature Request] A way to hide untoggled encounters.

### ISSUE THREAD

**Issue by gotex007** [mythridium/combat-simulator#56]
There are so many monsters, dungeons, etc in the game. Could there be a way added to actually hide untoggled targets so I can scroll through the list easier? I see that there's an option to shrink the icons by around 25% but if it wouldn't be difficult to add a way to hide the untoggled options entirely that would be appreciated.

**Comment by mythridium** [comment]
Thanks for this request, but this is not something I can action, I've already added numerous features such as the icon size as you've seen, and also a search field that lets you navigate directly to a target.

The reason for not hiding bars is technical. The performance of the plotter is a major concern and hiding/unhiding the bars will result in layout thrashing which causes the entire screen to freeze while the browser re-paints the view. This is even worse on slower devices such as phones.

I'd need to re-write the plotter entirely with a different solution of rendering the plotter, but this is not feasible at this time with the amount of work that would require.

I know this has been requested many times and if I find the time, will be something I look into, but for now will close this issue.

Thanks again for the request.
