### ISSUE TITLE
[Feature Request] A way to exclude encounters where I have a non-zero expected death rate when doing an "all" sim.

### ISSUE THREAD

**Issue by gotex007** [mythridium/combat-simulator#57]
It would be nice to not have to double check every encounter to make sure I won't die if I put the game down for 15 hours due to a very small chance of dying not coloring the bar. I think there used to be an option to disable "heal after death" that I can't seem to find anymore but didn't seem to do what I would expect it to anyway.

**Comment by mythridium** [comment]
Heal after Death was removed as a setting, but that wouldn't help with your case as you'd still die in combat sim.

I think what your asking for is not feasible, you want to exclude encounters where you have a death rate, but to get this information you need to run combat sim in the first place, you'd essentially be running it twice.

I think the tools are already in place to make it clear if something can kill you.

There is a filter which lets you quite easily see exactly which encounters result in a death.

Simulate all and then switch the filter to estimated death rate. You can then easily scroll through the plotter and every monster you die to should be fairly easy to see.

![image](https://github.com/user-attachments/assets/6dc718f2-dde2-48ae-8130-8bbb08216738)

In the same vein, if you are fighting a specific monster, the death rate will always be highlighted in red if you die at all during the simulation.

![image](https://github.com/user-attachments/assets/ff4923cf-6c58-4b24-b4e9-8ae7a646d04f)

If you are doing slayer tasks, then go all the way to right and sim against the slayer task itself, you can even inspect it to see just the monsters in the task and filter as above and you can see which monsters in the slayer task would kill you and which won't.

**Comment by gotex007** [comment]
Well sometimes it's like 0.0002 and the bar is still green and the estimated death bar is a sliver. I could flip back and forth between estimated death rate and most efficient for exp to find something to farm that can't kill me, but I was hoping there would be another solution. I'll manage though.
