### ISSUE TITLE
[Feature Request] Min/Maxing equipment from selected target

### ISSUE THREAD

**Issue by emfleck** [mythridium/combat-simulator#58]
Using the currently selected target, running through permutations and combinations of available equipment (either limited to items in bank or everything available) to select BiS equipment items to maximize different categories.  ie, exp, drops, etc.

**Comment by mythridium** [comment]
This is not something that is feasible to implement for various technical reasons and this is also not a direction I want to take combat sim.

At it's core, combat sim is one direction and a tool to aid the players decision, data goes from the game into sim and it outputs results based on your input, combat sim does not make decisions for you.
