### ISSUE TITLE
Presented with "simulation error: Cannot read properties of undefined (reading 'get')" error on v2.1.10.

### ISSUE THREAD

**Issue by BrianReckliss** [mythridium/combat-simulator#6]
**Description**
Presented with "simulation error: Cannot read properties of undefined (reading 'get')" error on v2.1.10.

**Steps to Reproduce**
1. Install and open Combat Simulator V2.1.10
2. Select "Plant" monster (or any other combatable monster).
3. Examine red text reading "No valid simulation data: entity not simulated."
4. Click "Import Set" for one of you combat sets.
5. Click "Simulate Selected"
6. Examine red error text at top-right indicating, "No valid simulation data: simulation error: Cannot read properties of undefined (reading 'get')."

**Expected Behavior**
Results of the simulation was expected.

**Screenshots**
![image](https://github.com/mythridium/combat-simulator/assets/6136329/0853d27a-54ae-4a4c-abdf-64a6493ebd3c)

**Device:**
Chrome Browser

**Additional context**
I previously used Combat Simulator Reloaded on this save which was uninstalled prior to installing [Myth] Combat Simulator.

**Save**
[Bug_Report_Exported_Save_2023-09-07.txt](https://github.com/mythridium/combat-simulator/files/12554827/Bug_Report_Exported_Save_2023-09-07.txt)

**Mod List**
- SEMI Core
- Unlimited Offline
- SEMI Auto Farming
- ETA
- Shop Item Owned Indicator
- Better Summoning Menu
- Item Uses
- Tiny Passive Icons
- Combat Indicators
- Quick Item/Bank Wiki
- SEMI Auto Gear Swap
- Show Slayer Tier
- Better Offline Recap
- SEMI Auto Runecrafting
- Upgrade All Potions
- AutoSort
- [Myth] Summoning
- [Myth] Combat Simulator

**Comment by mythridium** [comment]
Thank you so much for your bug report, I've released a fix for this issue.

Fixed in 39fbadd
