### ISSUE TITLE
Combat sim fails give the correct value for barrier dust received when enemies have their max health reduced

### ISSUE THREAD

**Issue by cookb0065** [mythridium/combat-simulator#61]
**Describe the bug**

The combat simulator does not accurately give the amount of barrier dust received from barrier monsters

**To Reproduce**

Simulate an encounter with any high level barrier monster while hitpoints relic 2 has been obtained. For example, merman is shown as dropping 15 barrier dust per kill, which is inaccurate.

**Expected behavior**

The amount of barrier dust is effectively calculated as such: max(floor(effective max hitpoints/2/10/20), 1). Hitpoints relic 2 reduces enemy effective max hitpoints by 15%. For example, this means that merman now drops 13 barrier dust instead of 15.

**Screenshots**

**Device:**
List if Steam, which Browser or Mobile
All

**Additional context**

**Save**
Attach your save file using one of the following:

https://melvoridle.com/save/Gyzrd3Ob

**Mod List**
Mod Manager > My Mods > Copy Mod List

SEMI Core
[Myth] Combat Simulator
Unlock Gamemodes
Unlimited Offline
Shop Item Owned Indicator
ETA
Show Item Sources And Uses
Multitasking (Disabled)
SEMI Drop Chances
SEMI Auto Farming (Disabled)
Mastery Pool Can Overflow (Disabled)
SEMI Auto Master (Disabled)
Show Skill Modifiers
SEMI Auto Loot (Disabled)
QuickShards
Absurdly High Max Township Storage (Disabled)
Semi Auto Township
Free Extra Bank Slots (Disabled)
Skilling Bosses (Beta) (Disabled)
[Myth] Mordecai (Disabled)
Shamanism (Disabled)
Remove Equipment Requirements (Disabled)
I hate RNG (Disabled)
I love RNG (Disabled)
Construction (Disabled)
Occultism (Disabled)
Sailing (Beta) (Disabled)

**Comment by mythridium** [comment]
Thanks for taking the time to report this issue.

I've released v3.1.16 which resolves this.

Fixed in [f7993cd](https://github.com/mythridium/combat-simulator/commit/f7993cd22215b22a4166240443cef2bdd0d914b2)
