### ISSUE TITLE
Wrong damage taken calculation on poison virulence set bonus

### ISSUE THREAD

**Issue by JakeStraker** [mythridium/combat-simulator#7]
**Describe the bug**
I seem to be getting higher than in-game damage taken on combat sim

**To Reproduce**
1. Go to 'Spectral Wolf` - Monster I was testing on
2. Use a poison virulence ring and a pair of 8% DR gloves, I used Terran in this case
3. Make note of the max his recieved, 588 in this case
4. Switch the 8% DR gloves to the poison virulence gloves,
5. Rerun the sim and make a note of the substantially higher max hit recieved 705 in this case

**Expected behavior**
Max hit recieved should be the same as the passive does not impact damage taken with or without poison.

**Screenshots**
Setup 1, 588 Max Damage Recieved: 
![image](https://github.com/mythridium/combat-simulator/assets/9753708/9ada227e-f9a0-4202-b8e4-7ee3c7f773b9)

Setup 2, 705 Max Damage Recieved:
![image](https://github.com/mythridium/combat-simulator/assets/9753708/c836867c-4da5-4d1b-92c5-37df7f34a05e)

**Device:**
Steam Client

**Additional context**
"finaljake" on discord

**Save**
Attach your save file using one of the following:
https://melvoridle.com/save/LdiZk50D

**Mod List**
Mod Manager > My Mods > Copy Mod List

Upgrade All Potions
ETA
[Myth] Combat Simulator

**Comment by mythridium** [comment]
Hey, thanks so much for reporting this issue.

I wasn't able to reproduce this with the gloves specifically, however there was a bug that modifiers that apply to the enemy were being applied to the player, this in particular would impact things like prayers.

Do you know if you had switched some of these around during your testing?

I think this should be fixed now with v2.1.14, do you mind checking to see if it works now for you?

**Comment by mythridium** [comment]
I believe this one has been fixed, if it's still an issue feel free to re-open this or create a new issue with any updated details as relevant. Thanks for the report!

Fixed in 235940774f6c0b4a6871986eb22f349e9b252e27
