### ISSUE TITLE
Support Agility blueprints

### ISSUE THREAD

**Issue by TimoDeus** [mythridium/combat-simulator#8]
As a player of Melvor I'd like to be able to load blueprints in combat simulator so that I can easily simulate with my combat course even when I'm currently using the skilling setup.

Right now Agility is prefilled with the course I'm using currently. Oftentimes I have a skilling course active, but want to prepare for the next combat session. It would be super helpful to switch to another saved blueprint.

Feature request, not a bug! Feel free to give this low priority.

**Comment by mythridium** [comment]
I've added support for this.

![image](https://github.com/mythridium/combat-simulator/assets/132613374/aad43c18-502f-40cb-93c6-cff5038bc2d3)

I've run over this and seems to work as expected, but let me know if you notice any bugs with it.

Added in ae2e6a70ccff7ae926e56a10185e757999f52702

**Comment by TimoDeus** [comment]
You are awesome! I can't test it on mobile due to [#4](https://github.com/mythridium/combat-simulator/issues/4), but still your rate of releasing improvements and bug fixes is really great.
